 
/* AUTOGENERATED FILE. DO NOT EDIT. */


  #include "unity.h"
  #include "unity_print.h"
#ifndef __codasip__
  #include "string.h"
#endif /* __codasip__ */


int verbose;

void  test_controller_build();
void  test_kex_including_node_state_machine_ssa();
void  test_kex_including_node_state_machine_csa();
void  test_kex_including_node_sond_complete();
void  test_kex_inclusion_timer_handling();
void  test_kex_inclusion_timeout_kex_get_with_retry();
void  test_kex_inclusion_timeout_kex_set_with_retry();
void  test_kex_inclusion_timeout_all_states();
void  test_kex_inclusion_duplicate_frame_order_all_states();
void  test_kex_inclusion_error_schemes();
void  test_kex_inclusion_error_curves();
void  test_kex_inclusion_error_keys();
void  test_kex_inclusion_valid_keys();
void  test_kex_inclusion_error_key_get_request();
void  test_kex_inclusion_key_grant_user_reject();
void  test_kex_inclusion_user_reject();
void  test_kex_inclusion_pending_user_accept_echo_kex_set_received();
void  test_kex_inclusion_error_multi_key_get_request();
void  test_kex_inclusion_error_public_key_including_bit();
void  test_kex_inclusion_public_key_reserved_bits();
void  test_kex_inclusion_error_echo_kex_set();
void  test_kex_inclusion_timeout_when_idle();
void  test_kex_including_node_key_grant_subset();
void  test_kex_including_node_decrypt_failed();
void  test_kex_invalid_crypt_frame_idle();
void  test_kex_inclusion_tx_queue_full();


#ifdef __C51__
#include "reg51.h"

void setUp() {
#if 1
SCON  = 0x50;                   /* SCON: mode 1, 8-bit UART, enable rcvr    */
TMOD |= 0x20;                   /* TMOD: timer 1, mode 2, 8-bit reload      */
TH1   = 0xf3;                   /* TH1:  reload value for 2400 baud         */
TR1   = 1;                      /* TR1:  timer 1 run                        */
TI    = 1;                      /* TI:   set TI to send first char of UART  */
#else
  int bBaudRate;
  WATCHDOG_DISABLE;
  bBaudRate = 1152;
  bBaudRate = (80000/bBaudRate ) + (((80000 %bBaudRate ) >= (bBaudRate >> 1))  ? 1:0);
  UART0_SET_BAUD_RATE(68);
  UART0_TX_ENABLE;
  
  OPEN_IOS
  UART0BUF = '*';
#endif

}

void tearDown() {

}

extern int main(void) {
    int i;
    int ret;
    
    verbose=0;
    unity_print_init();
    UNITY_BEGIN();


    UnityDefaultTestRun(&test_controller_build, "test_controller_build",  191 );
    UnityDefaultTestRun(&test_kex_including_node_state_machine_ssa, "test_kex_including_node_state_machine_ssa",  505 );
    UnityDefaultTestRun(&test_kex_including_node_state_machine_csa, "test_kex_including_node_state_machine_csa",  508 );
    UnityDefaultTestRun(&test_kex_including_node_sond_complete, "test_kex_including_node_sond_complete",  516 );
    UnityDefaultTestRun(&test_kex_inclusion_timer_handling, "test_kex_inclusion_timer_handling",  650 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_kex_get_with_retry, "test_kex_inclusion_timeout_kex_get_with_retry",  760 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_kex_set_with_retry, "test_kex_inclusion_timeout_kex_set_with_retry",  842 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_all_states, "test_kex_inclusion_timeout_all_states",  936 );
    UnityDefaultTestRun(&test_kex_inclusion_duplicate_frame_order_all_states, "test_kex_inclusion_duplicate_frame_order_all_states",  1459 );
    UnityDefaultTestRun(&test_kex_inclusion_error_schemes, "test_kex_inclusion_error_schemes",  1666 );
    UnityDefaultTestRun(&test_kex_inclusion_error_curves, "test_kex_inclusion_error_curves",  1749 );
    UnityDefaultTestRun(&test_kex_inclusion_error_keys, "test_kex_inclusion_error_keys",  1821 );
    UnityDefaultTestRun(&test_kex_inclusion_valid_keys, "test_kex_inclusion_valid_keys",  1902 );
    UnityDefaultTestRun(&test_kex_inclusion_error_key_get_request, "test_kex_inclusion_error_key_get_request",  1998 );
    UnityDefaultTestRun(&test_kex_inclusion_key_grant_user_reject, "test_kex_inclusion_key_grant_user_reject",  2202 );
    UnityDefaultTestRun(&test_kex_inclusion_user_reject, "test_kex_inclusion_user_reject",  2283 );
    UnityDefaultTestRun(&test_kex_inclusion_pending_user_accept_echo_kex_set_received, "test_kex_inclusion_pending_user_accept_echo_kex_set_received",  2393 );
    UnityDefaultTestRun(&test_kex_inclusion_error_multi_key_get_request, "test_kex_inclusion_error_multi_key_get_request",  2500 );
    UnityDefaultTestRun(&test_kex_inclusion_error_public_key_including_bit, "test_kex_inclusion_error_public_key_including_bit",  2665 );
    UnityDefaultTestRun(&test_kex_inclusion_public_key_reserved_bits, "test_kex_inclusion_public_key_reserved_bits",  2752 );
    UnityDefaultTestRun(&test_kex_inclusion_error_echo_kex_set, "test_kex_inclusion_error_echo_kex_set",  2944 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_when_idle, "test_kex_inclusion_timeout_when_idle",  3143 );
    UnityDefaultTestRun(&test_kex_including_node_key_grant_subset, "test_kex_including_node_key_grant_subset",  3182 );
    UnityDefaultTestRun(&test_kex_including_node_decrypt_failed, "test_kex_including_node_decrypt_failed",  3405 );
    UnityDefaultTestRun(&test_kex_invalid_crypt_frame_idle, "test_kex_invalid_crypt_frame_idle",  3559 );
    UnityDefaultTestRun(&test_kex_inclusion_tx_queue_full, "test_kex_inclusion_tx_queue_full",  3590 );

    ret = UNITY_END();
    unity_print_close();
    while(1);
}
#else
int main(int argc, char** argp) {
    int ret;
    unity_print_init();
    UNITY_BEGIN();


    UnityDefaultTestRun(&test_controller_build, "test_controller_build",  191 );
    UnityDefaultTestRun(&test_kex_including_node_state_machine_ssa, "test_kex_including_node_state_machine_ssa",  505 );
    UnityDefaultTestRun(&test_kex_including_node_state_machine_csa, "test_kex_including_node_state_machine_csa",  508 );
    UnityDefaultTestRun(&test_kex_including_node_sond_complete, "test_kex_including_node_sond_complete",  516 );
    UnityDefaultTestRun(&test_kex_inclusion_timer_handling, "test_kex_inclusion_timer_handling",  650 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_kex_get_with_retry, "test_kex_inclusion_timeout_kex_get_with_retry",  760 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_kex_set_with_retry, "test_kex_inclusion_timeout_kex_set_with_retry",  842 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_all_states, "test_kex_inclusion_timeout_all_states",  936 );
    UnityDefaultTestRun(&test_kex_inclusion_duplicate_frame_order_all_states, "test_kex_inclusion_duplicate_frame_order_all_states",  1459 );
    UnityDefaultTestRun(&test_kex_inclusion_error_schemes, "test_kex_inclusion_error_schemes",  1666 );
    UnityDefaultTestRun(&test_kex_inclusion_error_curves, "test_kex_inclusion_error_curves",  1749 );
    UnityDefaultTestRun(&test_kex_inclusion_error_keys, "test_kex_inclusion_error_keys",  1821 );
    UnityDefaultTestRun(&test_kex_inclusion_valid_keys, "test_kex_inclusion_valid_keys",  1902 );
    UnityDefaultTestRun(&test_kex_inclusion_error_key_get_request, "test_kex_inclusion_error_key_get_request",  1998 );
    UnityDefaultTestRun(&test_kex_inclusion_key_grant_user_reject, "test_kex_inclusion_key_grant_user_reject",  2202 );
    UnityDefaultTestRun(&test_kex_inclusion_user_reject, "test_kex_inclusion_user_reject",  2283 );
    UnityDefaultTestRun(&test_kex_inclusion_pending_user_accept_echo_kex_set_received, "test_kex_inclusion_pending_user_accept_echo_kex_set_received",  2393 );
    UnityDefaultTestRun(&test_kex_inclusion_error_multi_key_get_request, "test_kex_inclusion_error_multi_key_get_request",  2500 );
    UnityDefaultTestRun(&test_kex_inclusion_error_public_key_including_bit, "test_kex_inclusion_error_public_key_including_bit",  2665 );
    UnityDefaultTestRun(&test_kex_inclusion_public_key_reserved_bits, "test_kex_inclusion_public_key_reserved_bits",  2752 );
    UnityDefaultTestRun(&test_kex_inclusion_error_echo_kex_set, "test_kex_inclusion_error_echo_kex_set",  2944 );
    UnityDefaultTestRun(&test_kex_inclusion_timeout_when_idle, "test_kex_inclusion_timeout_when_idle",  3143 );
    UnityDefaultTestRun(&test_kex_including_node_key_grant_subset, "test_kex_including_node_key_grant_subset",  3182 );
    UnityDefaultTestRun(&test_kex_including_node_decrypt_failed, "test_kex_including_node_decrypt_failed",  3405 );
    UnityDefaultTestRun(&test_kex_invalid_crypt_frame_idle, "test_kex_invalid_crypt_frame_idle",  3559 );
    UnityDefaultTestRun(&test_kex_inclusion_tx_queue_full, "test_kex_inclusion_tx_queue_full",  3590 );

    ret = UNITY_END();
    unity_print_close();
    return ret;
}
#endif


