 
/* AUTOGENERATED FILE. DO NOT EDIT. */


  #include "unity.h"
  #include "unity_print.h"
#ifndef __codasip__
  #include "string.h"
#endif /* __codasip__ */


int verbose;

void  test_s2_send_data();
void  test_single_frame_transmission();
void  test_send_data_fail_in_nonce_get();
void  test_transmit_complete_no_ack_in_nonce_get();
void  test_transmit_timeout_after_sending_nonce_get();
void  test_transmit_timeout_before_sending_nonce_get();
void  test_dup_nonce_get();
void  test_send_data_fail_in_encap_message();
void  test_send_data_no_ack_in_encap_message();
void  test_encap_seq_increase();
void  test_nonce_report();
void  test_sos_recover_scenario1();
void  test_sos_recover_scenario2();
void  test_encap_message_authcheck();
void  test_hdr_ext_zero_length_and_more_to_follow();
void  test_hdr_ext_zero_length_and_more_to_follow2();
void  test_encap_message_oversize();
void  test_encap_message_lencheck();
void  test_encap_message_extcheck();
void  test_encap_message_critical_extcheck();
void  test_encap_message_extlen();
void  test_m_enacap_send();
void  test_commands_supported_report();
void  test_sd_verify_tx_ok();
void  test_sd_verify_tx_ok_second_attempt();
void  test_sd_verify_tx_fail();
void  test_sd_verify_tx_verifify();
void  test_sd_verify_tx_verify_second_attempt();
void  test_mulicast_send();
void  test_mulicast_send_mos_sos_sync();
void  test_s2_send_data_second_group();


#ifdef __C51__
#include "reg51.h"

void setUp() {
#if 1
SCON  = 0x50;                   /* SCON: mode 1, 8-bit UART, enable rcvr    */
TMOD |= 0x20;                   /* TMOD: timer 1, mode 2, 8-bit reload      */
TH1   = 0xf3;                   /* TH1:  reload value for 2400 baud         */
TR1   = 1;                      /* TR1:  timer 1 run                        */
TI    = 1;                      /* TI:   set TI to send first char of UART  */
#else
  int bBaudRate;
  WATCHDOG_DISABLE;
  bBaudRate = 1152;
  bBaudRate = (80000/bBaudRate ) + (((80000 %bBaudRate ) >= (bBaudRate >> 1))  ? 1:0);
  UART0_SET_BAUD_RATE(68);
  UART0_TX_ENABLE;
  
  OPEN_IOS
  UART0BUF = '*';
#endif

}

void tearDown() {

}

extern int main(void) {
    int i;
    int ret;
    
    verbose=0;
    unity_print_init();
    UNITY_BEGIN();


    UnityDefaultTestRun(&test_s2_send_data, "test_s2_send_data",  357 );
    UnityDefaultTestRun(&test_single_frame_transmission, "test_single_frame_transmission",  371 );
    UnityDefaultTestRun(&test_send_data_fail_in_nonce_get, "test_send_data_fail_in_nonce_get",  401 );
    UnityDefaultTestRun(&test_transmit_complete_no_ack_in_nonce_get, "test_transmit_complete_no_ack_in_nonce_get",  413 );
    UnityDefaultTestRun(&test_transmit_timeout_after_sending_nonce_get, "test_transmit_timeout_after_sending_nonce_get",  429 );
    UnityDefaultTestRun(&test_transmit_timeout_before_sending_nonce_get, "test_transmit_timeout_before_sending_nonce_get",  446 );
    UnityDefaultTestRun(&test_dup_nonce_get, "test_dup_nonce_get",  465 );
    UnityDefaultTestRun(&test_send_data_fail_in_encap_message, "test_send_data_fail_in_encap_message",  530 );
    UnityDefaultTestRun(&test_send_data_no_ack_in_encap_message, "test_send_data_no_ack_in_encap_message",  553 );
    UnityDefaultTestRun(&test_encap_seq_increase, "test_encap_seq_increase",  579 );
    UnityDefaultTestRun(&test_nonce_report, "test_nonce_report",  624 );
    UnityDefaultTestRun(&test_sos_recover_scenario1, "test_sos_recover_scenario1",  689 );
    UnityDefaultTestRun(&test_sos_recover_scenario2, "test_sos_recover_scenario2",  759 );
    UnityDefaultTestRun(&test_encap_message_authcheck, "test_encap_message_authcheck",  835 );
    UnityDefaultTestRun(&test_hdr_ext_zero_length_and_more_to_follow, "test_hdr_ext_zero_length_and_more_to_follow",  858 );
    UnityDefaultTestRun(&test_hdr_ext_zero_length_and_more_to_follow2, "test_hdr_ext_zero_length_and_more_to_follow2",  877 );
    UnityDefaultTestRun(&test_encap_message_oversize, "test_encap_message_oversize",  893 );
    UnityDefaultTestRun(&test_encap_message_lencheck, "test_encap_message_lencheck",  904 );
    UnityDefaultTestRun(&test_encap_message_extcheck, "test_encap_message_extcheck",  915 );
    UnityDefaultTestRun(&test_encap_message_critical_extcheck, "test_encap_message_critical_extcheck",  924 );
    UnityDefaultTestRun(&test_encap_message_extlen, "test_encap_message_extlen",  933 );
    UnityDefaultTestRun(&test_m_enacap_send, "test_m_enacap_send",  943 );
    UnityDefaultTestRun(&test_commands_supported_report, "test_commands_supported_report",  965 );
    UnityDefaultTestRun(&test_sd_verify_tx_ok, "test_sd_verify_tx_ok",  1001 );
    UnityDefaultTestRun(&test_sd_verify_tx_ok_second_attempt, "test_sd_verify_tx_ok_second_attempt",  1042 );
    UnityDefaultTestRun(&test_sd_verify_tx_fail, "test_sd_verify_tx_fail",  1104 );
    UnityDefaultTestRun(&test_sd_verify_tx_verifify, "test_sd_verify_tx_verifify",  1175 );
    UnityDefaultTestRun(&test_sd_verify_tx_verify_second_attempt, "test_sd_verify_tx_verify_second_attempt",  1232 );
    UnityDefaultTestRun(&test_mulicast_send, "test_mulicast_send",  1468 );
    UnityDefaultTestRun(&test_mulicast_send_mos_sos_sync, "test_mulicast_send_mos_sos_sync",  1553 );
    UnityDefaultTestRun(&test_s2_send_data_second_group, "test_s2_send_data_second_group",  1680 );

    ret = UNITY_END();
    unity_print_close();
    while(1);
}
#else
int main(int argc, char** argp) {
    int ret;
    unity_print_init();
    UNITY_BEGIN();


    UnityDefaultTestRun(&test_s2_send_data, "test_s2_send_data",  357 );
    UnityDefaultTestRun(&test_single_frame_transmission, "test_single_frame_transmission",  371 );
    UnityDefaultTestRun(&test_send_data_fail_in_nonce_get, "test_send_data_fail_in_nonce_get",  401 );
    UnityDefaultTestRun(&test_transmit_complete_no_ack_in_nonce_get, "test_transmit_complete_no_ack_in_nonce_get",  413 );
    UnityDefaultTestRun(&test_transmit_timeout_after_sending_nonce_get, "test_transmit_timeout_after_sending_nonce_get",  429 );
    UnityDefaultTestRun(&test_transmit_timeout_before_sending_nonce_get, "test_transmit_timeout_before_sending_nonce_get",  446 );
    UnityDefaultTestRun(&test_dup_nonce_get, "test_dup_nonce_get",  465 );
    UnityDefaultTestRun(&test_send_data_fail_in_encap_message, "test_send_data_fail_in_encap_message",  530 );
    UnityDefaultTestRun(&test_send_data_no_ack_in_encap_message, "test_send_data_no_ack_in_encap_message",  553 );
    UnityDefaultTestRun(&test_encap_seq_increase, "test_encap_seq_increase",  579 );
    UnityDefaultTestRun(&test_nonce_report, "test_nonce_report",  624 );
    UnityDefaultTestRun(&test_sos_recover_scenario1, "test_sos_recover_scenario1",  689 );
    UnityDefaultTestRun(&test_sos_recover_scenario2, "test_sos_recover_scenario2",  759 );
    UnityDefaultTestRun(&test_encap_message_authcheck, "test_encap_message_authcheck",  835 );
    UnityDefaultTestRun(&test_hdr_ext_zero_length_and_more_to_follow, "test_hdr_ext_zero_length_and_more_to_follow",  858 );
    UnityDefaultTestRun(&test_hdr_ext_zero_length_and_more_to_follow2, "test_hdr_ext_zero_length_and_more_to_follow2",  877 );
    UnityDefaultTestRun(&test_encap_message_oversize, "test_encap_message_oversize",  893 );
    UnityDefaultTestRun(&test_encap_message_lencheck, "test_encap_message_lencheck",  904 );
    UnityDefaultTestRun(&test_encap_message_extcheck, "test_encap_message_extcheck",  915 );
    UnityDefaultTestRun(&test_encap_message_critical_extcheck, "test_encap_message_critical_extcheck",  924 );
    UnityDefaultTestRun(&test_encap_message_extlen, "test_encap_message_extlen",  933 );
    UnityDefaultTestRun(&test_m_enacap_send, "test_m_enacap_send",  943 );
    UnityDefaultTestRun(&test_commands_supported_report, "test_commands_supported_report",  965 );
    UnityDefaultTestRun(&test_sd_verify_tx_ok, "test_sd_verify_tx_ok",  1001 );
    UnityDefaultTestRun(&test_sd_verify_tx_ok_second_attempt, "test_sd_verify_tx_ok_second_attempt",  1042 );
    UnityDefaultTestRun(&test_sd_verify_tx_fail, "test_sd_verify_tx_fail",  1104 );
    UnityDefaultTestRun(&test_sd_verify_tx_verifify, "test_sd_verify_tx_verifify",  1175 );
    UnityDefaultTestRun(&test_sd_verify_tx_verify_second_attempt, "test_sd_verify_tx_verify_second_attempt",  1232 );
    UnityDefaultTestRun(&test_mulicast_send, "test_mulicast_send",  1468 );
    UnityDefaultTestRun(&test_mulicast_send_mos_sos_sync, "test_mulicast_send_mos_sos_sync",  1553 );
    UnityDefaultTestRun(&test_s2_send_data_second_group, "test_s2_send_data_second_group",  1680 );

    ret = UNITY_END();
    unity_print_close();
    return ret;
}
#endif


