package com.askey.firefly.zwave.control.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZWAVE_DEVICE".
*/
public class ZwaveDeviceDao extends AbstractDao<ZwaveDevice, Long> {

    public static final String TABLENAME = "ZWAVE_DEVICE";

    /**
     * Properties of entity ZwaveDevice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ZwaveId = new Property(0, Long.class, "zwaveId", true, "_id");
        public final static Property Brand = new Property(1, String.class, "brand", false, "brand");
        public final static Property NodeId = new Property(2, Integer.class, "nodeId", false, "nodeId");
        public final static Property Name = new Property(3, String.class, "name", false, "name");
        public final static Property DevType = new Property(4, String.class, "devType", false, "devType");
        public final static Property Category = new Property(5, String.class, "category", false, "category");
        public final static Property RoomName = new Property(6, String.class, "roomName", false, "roomName");
        public final static Property IsFavorite = new Property(7, String.class, "isFavorite", false, "isFavorite");
        public final static Property InterfaceId = new Property(8, Integer.class, "interfaceId", false, "interfaceId");
        public final static Property NodeInfo = new Property(9, String.class, "nodeInfo", false, "nodeInfo");
        public final static Property Timestamp = new Property(10, Long.class, "timestamp", false, "timestamp");
    }

    private Query<ZwaveDevice> zwaveDeviceGroup_ZwaveDeviceListQuery;
    private Query<ZwaveDevice> zwaveDeviceRoom_ZwaveDeviceListQuery;

    public ZwaveDeviceDao(DaoConfig config) {
        super(config);
    }
    
    public ZwaveDeviceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ZwaveDevice entity) {
        stmt.clearBindings();
 
        Long zwaveId = entity.getZwaveId();
        if (zwaveId != null) {
            stmt.bindLong(1, zwaveId);
        }
 
        String brand = entity.getBrand();
        if (brand != null) {
            stmt.bindString(2, brand);
        }
 
        Integer nodeId = entity.getNodeId();
        if (nodeId != null) {
            stmt.bindLong(3, nodeId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String devType = entity.getDevType();
        if (devType != null) {
            stmt.bindString(5, devType);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(6, category);
        }
 
        String roomName = entity.getRoomName();
        if (roomName != null) {
            stmt.bindString(7, roomName);
        }
 
        String isFavorite = entity.getIsFavorite();
        if (isFavorite != null) {
            stmt.bindString(8, isFavorite);
        }
 
        Integer interfaceId = entity.getInterfaceId();
        if (interfaceId != null) {
            stmt.bindLong(9, interfaceId);
        }
 
        String nodeInfo = entity.getNodeInfo();
        if (nodeInfo != null) {
            stmt.bindString(10, nodeInfo);
        }
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(11, timestamp);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ZwaveDevice entity) {
        stmt.clearBindings();
 
        Long zwaveId = entity.getZwaveId();
        if (zwaveId != null) {
            stmt.bindLong(1, zwaveId);
        }
 
        String brand = entity.getBrand();
        if (brand != null) {
            stmt.bindString(2, brand);
        }
 
        Integer nodeId = entity.getNodeId();
        if (nodeId != null) {
            stmt.bindLong(3, nodeId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String devType = entity.getDevType();
        if (devType != null) {
            stmt.bindString(5, devType);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(6, category);
        }
 
        String roomName = entity.getRoomName();
        if (roomName != null) {
            stmt.bindString(7, roomName);
        }
 
        String isFavorite = entity.getIsFavorite();
        if (isFavorite != null) {
            stmt.bindString(8, isFavorite);
        }
 
        Integer interfaceId = entity.getInterfaceId();
        if (interfaceId != null) {
            stmt.bindLong(9, interfaceId);
        }
 
        String nodeInfo = entity.getNodeInfo();
        if (nodeInfo != null) {
            stmt.bindString(10, nodeInfo);
        }
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(11, timestamp);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ZwaveDevice readEntity(Cursor cursor, int offset) {
        ZwaveDevice entity = new ZwaveDevice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // zwaveId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // brand
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // nodeId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // devType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // category
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // roomName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // isFavorite
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // interfaceId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // nodeInfo
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // timestamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ZwaveDevice entity, int offset) {
        entity.setZwaveId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBrand(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNodeId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDevType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCategory(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRoomName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsFavorite(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setInterfaceId(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setNodeInfo(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTimestamp(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ZwaveDevice entity, long rowId) {
        entity.setZwaveId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ZwaveDevice entity) {
        if(entity != null) {
            return entity.getZwaveId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ZwaveDevice entity) {
        return entity.getZwaveId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "zwaveDeviceList" to-many relationship of ZwaveDeviceGroup. */
    public List<ZwaveDevice> _queryZwaveDeviceGroup_ZwaveDeviceList(Integer nodeId) {
        synchronized (this) {
            if (zwaveDeviceGroup_ZwaveDeviceListQuery == null) {
                QueryBuilder<ZwaveDevice> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.NodeId.eq(null));
                zwaveDeviceGroup_ZwaveDeviceListQuery = queryBuilder.build();
            }
        }
        Query<ZwaveDevice> query = zwaveDeviceGroup_ZwaveDeviceListQuery.forCurrentThread();
        query.setParameter(0, nodeId);
        return query.list();
    }

    /** Internal query to resolve the "zwaveDeviceList" to-many relationship of ZwaveDeviceRoom. */
    public List<ZwaveDevice> _queryZwaveDeviceRoom_ZwaveDeviceList(String roomName) {
        synchronized (this) {
            if (zwaveDeviceRoom_ZwaveDeviceListQuery == null) {
                QueryBuilder<ZwaveDevice> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RoomName.eq(null));
                zwaveDeviceRoom_ZwaveDeviceListQuery = queryBuilder.build();
            }
        }
        Query<ZwaveDevice> query = zwaveDeviceRoom_ZwaveDeviceListQuery.forCurrentThread();
        query.setParameter(0, roomName);
        return query.list();
    }

}
