package com.askey.iotcontrol.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.askey.iotcontrol.dao.ZwaveDevice;
import com.askey.iotcontrol.dao.ZwaveDeviceGroup;
import com.askey.iotcontrol.dao.ZwaveDeviceRoom;
import com.askey.iotcontrol.dao.ZwaveDeviceScene;
import com.askey.iotcontrol.dao.ZwaveScene;
import com.askey.iotcontrol.dao.ZwaveSchedule;

import com.askey.iotcontrol.dao.ZwaveDeviceDao;
import com.askey.iotcontrol.dao.ZwaveDeviceGroupDao;
import com.askey.iotcontrol.dao.ZwaveDeviceRoomDao;
import com.askey.iotcontrol.dao.ZwaveDeviceSceneDao;
import com.askey.iotcontrol.dao.ZwaveSceneDao;
import com.askey.iotcontrol.dao.ZwaveScheduleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zwaveDeviceDaoConfig;
    private final DaoConfig zwaveDeviceGroupDaoConfig;
    private final DaoConfig zwaveDeviceRoomDaoConfig;
    private final DaoConfig zwaveDeviceSceneDaoConfig;
    private final DaoConfig zwaveSceneDaoConfig;
    private final DaoConfig zwaveScheduleDaoConfig;

    private final ZwaveDeviceDao zwaveDeviceDao;
    private final ZwaveDeviceGroupDao zwaveDeviceGroupDao;
    private final ZwaveDeviceRoomDao zwaveDeviceRoomDao;
    private final ZwaveDeviceSceneDao zwaveDeviceSceneDao;
    private final ZwaveSceneDao zwaveSceneDao;
    private final ZwaveScheduleDao zwaveScheduleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zwaveDeviceDaoConfig = daoConfigMap.get(ZwaveDeviceDao.class).clone();
        zwaveDeviceDaoConfig.initIdentityScope(type);

        zwaveDeviceGroupDaoConfig = daoConfigMap.get(ZwaveDeviceGroupDao.class).clone();
        zwaveDeviceGroupDaoConfig.initIdentityScope(type);

        zwaveDeviceRoomDaoConfig = daoConfigMap.get(ZwaveDeviceRoomDao.class).clone();
        zwaveDeviceRoomDaoConfig.initIdentityScope(type);

        zwaveDeviceSceneDaoConfig = daoConfigMap.get(ZwaveDeviceSceneDao.class).clone();
        zwaveDeviceSceneDaoConfig.initIdentityScope(type);

        zwaveSceneDaoConfig = daoConfigMap.get(ZwaveSceneDao.class).clone();
        zwaveSceneDaoConfig.initIdentityScope(type);

        zwaveScheduleDaoConfig = daoConfigMap.get(ZwaveScheduleDao.class).clone();
        zwaveScheduleDaoConfig.initIdentityScope(type);

        zwaveDeviceDao = new ZwaveDeviceDao(zwaveDeviceDaoConfig, this);
        zwaveDeviceGroupDao = new ZwaveDeviceGroupDao(zwaveDeviceGroupDaoConfig, this);
        zwaveDeviceRoomDao = new ZwaveDeviceRoomDao(zwaveDeviceRoomDaoConfig, this);
        zwaveDeviceSceneDao = new ZwaveDeviceSceneDao(zwaveDeviceSceneDaoConfig, this);
        zwaveSceneDao = new ZwaveSceneDao(zwaveSceneDaoConfig, this);
        zwaveScheduleDao = new ZwaveScheduleDao(zwaveScheduleDaoConfig, this);

        registerDao(ZwaveDevice.class, zwaveDeviceDao);
        registerDao(ZwaveDeviceGroup.class, zwaveDeviceGroupDao);
        registerDao(ZwaveDeviceRoom.class, zwaveDeviceRoomDao);
        registerDao(ZwaveDeviceScene.class, zwaveDeviceSceneDao);
        registerDao(ZwaveScene.class, zwaveSceneDao);
        registerDao(ZwaveSchedule.class, zwaveScheduleDao);
    }
    
    public void clear() {
        zwaveDeviceDaoConfig.clearIdentityScope();
        zwaveDeviceGroupDaoConfig.clearIdentityScope();
        zwaveDeviceRoomDaoConfig.clearIdentityScope();
        zwaveDeviceSceneDaoConfig.clearIdentityScope();
        zwaveSceneDaoConfig.clearIdentityScope();
        zwaveScheduleDaoConfig.clearIdentityScope();
    }

    public ZwaveDeviceDao getZwaveDeviceDao() {
        return zwaveDeviceDao;
    }

    public ZwaveDeviceGroupDao getZwaveDeviceGroupDao() {
        return zwaveDeviceGroupDao;
    }

    public ZwaveDeviceRoomDao getZwaveDeviceRoomDao() {
        return zwaveDeviceRoomDao;
    }

    public ZwaveDeviceSceneDao getZwaveDeviceSceneDao() {
        return zwaveDeviceSceneDao;
    }

    public ZwaveSceneDao getZwaveSceneDao() {
        return zwaveSceneDao;
    }

    public ZwaveScheduleDao getZwaveScheduleDao() {
        return zwaveScheduleDao;
    }

}
