package com.askey.iotcontrol.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZWAVE_SCENE".
*/
public class ZwaveSceneDao extends AbstractDao<ZwaveScene, Long> {

    public static final String TABLENAME = "ZWAVE_SCENE";

    /**
     * Properties of entity ZwaveScene.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SceneId = new Property(0, Long.class, "sceneId", true, "_id");
        public final static Property SceneName = new Property(1, String.class, "sceneName", false, "sceneName");
        public final static Property SceneIcon = new Property(2, String.class, "sceneIcon", false, "sceneIcon");
    }

    private DaoSession daoSession;


    public ZwaveSceneDao(DaoConfig config) {
        super(config);
    }
    
    public ZwaveSceneDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ZwaveScene entity) {
        stmt.clearBindings();
 
        Long sceneId = entity.getSceneId();
        if (sceneId != null) {
            stmt.bindLong(1, sceneId);
        }
 
        String sceneName = entity.getSceneName();
        if (sceneName != null) {
            stmt.bindString(2, sceneName);
        }
 
        String sceneIcon = entity.getSceneIcon();
        if (sceneIcon != null) {
            stmt.bindString(3, sceneIcon);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ZwaveScene entity) {
        stmt.clearBindings();
 
        Long sceneId = entity.getSceneId();
        if (sceneId != null) {
            stmt.bindLong(1, sceneId);
        }
 
        String sceneName = entity.getSceneName();
        if (sceneName != null) {
            stmt.bindString(2, sceneName);
        }
 
        String sceneIcon = entity.getSceneIcon();
        if (sceneIcon != null) {
            stmt.bindString(3, sceneIcon);
        }
    }

    @Override
    protected final void attachEntity(ZwaveScene entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ZwaveScene readEntity(Cursor cursor, int offset) {
        ZwaveScene entity = new ZwaveScene( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // sceneId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sceneName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // sceneIcon
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ZwaveScene entity, int offset) {
        entity.setSceneId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSceneName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSceneIcon(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ZwaveScene entity, long rowId) {
        entity.setSceneId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ZwaveScene entity) {
        if(entity != null) {
            return entity.getSceneId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ZwaveScene entity) {
        return entity.getSceneId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
