 
/* AUTOGENERATED FILE. DO NOT EDIT. */


  #include "unity.h"
  #include "unity_print.h"
#ifndef __codasip__
  #include "string.h"
#endif /* __codasip__ */


int verbose;

void  test_subkey_generation();
void  test_cmac_ietf_rfc4493_test_vectors_example_1();
void  test_cmac_ietf_rfc4493_test_vectors_example_2();
void  test_cmac_ietf_rfc4493_test_vectors_example_3();
void  test_cmac_ietf_rfc4493_test_vectors_example_4();
void  test_cmac_ietf_rfc4493_test_vectors_example_4_verify();
void  test_cmac_ietf_rfc4493_test_vectors_example_4_verify_negative();
void  test_cmac_xor_120();
void  test_cmac_leftshift_onebit();
void  test_cmac_padding();


#ifdef __C51__
#include "reg51.h"

void setUp() {
#if 1
SCON  = 0x50;                   /* SCON: mode 1, 8-bit UART, enable rcvr    */
TMOD |= 0x20;                   /* TMOD: timer 1, mode 2, 8-bit reload      */
TH1   = 0xf3;                   /* TH1:  reload value for 2400 baud         */
TR1   = 1;                      /* TR1:  timer 1 run                        */
TI    = 1;                      /* TI:   set TI to send first char of UART  */
#else
  int bBaudRate;
  WATCHDOG_DISABLE;
  bBaudRate = 1152;
  bBaudRate = (80000/bBaudRate ) + (((80000 %bBaudRate ) >= (bBaudRate >> 1))  ? 1:0);
  UART0_SET_BAUD_RATE(68);
  UART0_TX_ENABLE;
  
  OPEN_IOS
  UART0BUF = '*';
#endif

}

void tearDown() {

}

extern int main(void) {
    int i;
    int ret;
    
    verbose=0;
    unity_print_init();
    UNITY_BEGIN();


    UnityDefaultTestRun(&test_subkey_generation, "test_subkey_generation",  89 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_1, "test_cmac_ietf_rfc4493_test_vectors_example_1",  103 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_2, "test_cmac_ietf_rfc4493_test_vectors_example_2",  113 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_3, "test_cmac_ietf_rfc4493_test_vectors_example_3",  124 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_4, "test_cmac_ietf_rfc4493_test_vectors_example_4",  137 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_4_verify, "test_cmac_ietf_rfc4493_test_vectors_example_4_verify",  151 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_4_verify_negative, "test_cmac_ietf_rfc4493_test_vectors_example_4_verify_negative",  168 );
    UnityDefaultTestRun(&test_cmac_xor_120, "test_cmac_xor_120",  183 );
    UnityDefaultTestRun(&test_cmac_leftshift_onebit, "test_cmac_leftshift_onebit",  199 );
    UnityDefaultTestRun(&test_cmac_padding, "test_cmac_padding",  214 );

    ret = UNITY_END();
    unity_print_close();
    while(1);
}
#else
int main(int argc, char** argp) {
    int ret;
    unity_print_init();
    UNITY_BEGIN();


    UnityDefaultTestRun(&test_subkey_generation, "test_subkey_generation",  89 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_1, "test_cmac_ietf_rfc4493_test_vectors_example_1",  103 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_2, "test_cmac_ietf_rfc4493_test_vectors_example_2",  113 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_3, "test_cmac_ietf_rfc4493_test_vectors_example_3",  124 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_4, "test_cmac_ietf_rfc4493_test_vectors_example_4",  137 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_4_verify, "test_cmac_ietf_rfc4493_test_vectors_example_4_verify",  151 );
    UnityDefaultTestRun(&test_cmac_ietf_rfc4493_test_vectors_example_4_verify_negative, "test_cmac_ietf_rfc4493_test_vectors_example_4_verify_negative",  168 );
    UnityDefaultTestRun(&test_cmac_xor_120, "test_cmac_xor_120",  183 );
    UnityDefaultTestRun(&test_cmac_leftshift_onebit, "test_cmac_leftshift_onebit",  199 );
    UnityDefaultTestRun(&test_cmac_padding, "test_cmac_padding",  214 );

    ret = UNITY_END();
    unity_print_close();
    return ret;
}
#endif


