package com.askey.firefly.zwave.control.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.askey.firefly.zwave.control.dao.ZwaveDevice;
import com.askey.firefly.zwave.control.dao.ZwaveDeviceScene;

import com.askey.firefly.zwave.control.dao.ZwaveDeviceDao;
import com.askey.firefly.zwave.control.dao.ZwaveDeviceSceneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zwaveDeviceDaoConfig;
    private final DaoConfig zwaveDeviceSceneDaoConfig;

    private final ZwaveDeviceDao zwaveDeviceDao;
    private final ZwaveDeviceSceneDao zwaveDeviceSceneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zwaveDeviceDaoConfig = daoConfigMap.get(ZwaveDeviceDao.class).clone();
        zwaveDeviceDaoConfig.initIdentityScope(type);

        zwaveDeviceSceneDaoConfig = daoConfigMap.get(ZwaveDeviceSceneDao.class).clone();
        zwaveDeviceSceneDaoConfig.initIdentityScope(type);

        zwaveDeviceDao = new ZwaveDeviceDao(zwaveDeviceDaoConfig, this);
        zwaveDeviceSceneDao = new ZwaveDeviceSceneDao(zwaveDeviceSceneDaoConfig, this);

        registerDao(ZwaveDevice.class, zwaveDeviceDao);
        registerDao(ZwaveDeviceScene.class, zwaveDeviceSceneDao);
    }
    
    public void clear() {
        zwaveDeviceDaoConfig.clearIdentityScope();
        zwaveDeviceSceneDaoConfig.clearIdentityScope();
    }

    public ZwaveDeviceDao getZwaveDeviceDao() {
        return zwaveDeviceDao;
    }

    public ZwaveDeviceSceneDao getZwaveDeviceSceneDao() {
        return zwaveDeviceSceneDao;
    }

}
